apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-ingestion-service-deployment
  labels:
    app: telemetry-ingestion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-ingestion-service
  template:
    metadata:
      labels:
        app: telemetry-ingestion-service
    spec:
      containers:
        - name: telemetry-ingestion-service
          image: telemetry-ingestion-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
            - name: SERVER_PORT
              value: "8081"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"