apiVersion: v1
kind: Service
metadata:
  name: telemetry-processing-alert-service
  labels:
    app: telemetry-processing-alert-service
spec:
  selector:
    app: telemetry-processing-alert-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP