apiVersion: v1
kind: Service
metadata:
  name: fleet-management-service
  labels:
    app: fleet-management-service
spec:
  selector:
    app: fleet-management-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort